// frontend/src/views/AuthCallback.vue
<script setup>
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const router = useRouter()
const authStore = useAuthStore()

onMounted(() => {
  const urlParams = new URLSearchParams(window.location.search)
  const token = urlParams.get('token')
  const userDataB64 = urlParams.get('user_data')

  if (token && userDataB64) {
    try {
      // Decode base64 user data
      const userDataStr = atob(userDataB64)
      const userData = JSON.parse(userDataStr)
      
      // Store in Pinia and localStorage
      authStore.setAuth(token, userData)
      
      console.log('Auth successful:', userData)
      router.push('/chat')
    } catch (e) {
      console.error('Failed to parse auth data:', e)
      router.push('/login?error=parse_failed')
    }
  } else {
    // Check for error
    const error = urlParams.get('error')
    if (error) {
      console.error('Auth error:', error)
      router.push(`/login?error=${error}`)
    } else {
      router.push('/login')
    }
  }
})
</script>

<template>
  <div class="callback-container">
    <div class="loader-card fade-in">
      <div class="spinner"></div>
      <p class="loader-text">Authenticating...</p>
      <p class="loader-subtext">Please wait while we verify your credentials</p>
    </div>
  </div>
</template>

<style scoped>
.callback-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--color-bg-dark);
}

.loader-card {
  text-align: center;
  padding: 48px;
}

.spinner {
  width: 48px;
  height: 48px;
  border: 4px solid var(--color-border);
  border-top-color: var(--color-primary);
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin: 0 auto 24px;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.loader-text {
  font-size: 18px;
  font-weight: 600;
  color: var(--color-text);
  margin-bottom: 8px;
}

.loader-subtext {
  font-size: 14px;
  color: var(--color-text-muted);
}
</style>

// frontend/app/auth-callback/page.tsx
import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/context/AuthContext';

export default function AuthCallbackPage() {
  const { login } = useAuth();
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    try {
      const params = new URLSearchParams(window.location.search);
      const token = params.get('token');
      const userDataEncoded = params.get('user_data');
      if (!token || !userDataEncoded) {
        setError('Missing token or user data');
        return;
      }
      const user = JSON.parse(atob(userDataEncoded));
      login(token, user);
      router.replace('/');
    } catch (err) {
      setError('Authentication failed');
    }
  }, [login, router]);

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center h-full py-20">
        <h1 className="text-2xl font-bold mb-4">Authentication Error</h1>
        <p className="text-red-600">{error}</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center justify-center h-full py-20">
      <h1 className="text-2xl font-bold mb-4">Authenticating...</h1>
      <p className="text-gray-600">Processing your login. Please wait.</p>
    </div>
  );
}
