// frontend/src/components/auth/AuthCallback.tsx
import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

const AuthCallback = () => {
  const navigate = useNavigate();

  useEffect(() => {
    const handleCallback = async () => {
      try {
        const urlParams = new URLSearchParams(window.location.search);
        const code = urlParams.get('code');

        if (!code) {
          throw new Error('No code provided');
        }

        const response = await fetch('/api/auth/saml/callback', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ code }),
        });

        if (!response.ok) {
          throw new Error('Authentication failed');
        }

        const data = await response.json();
        
        // บันทึกข้อมูล token
        localStorage.setItem('auth_token', data.token);
        
        // บันทึกข้อมูลผู้ใช้
        localStorage.setItem('user_data', JSON.stringify({
          email: data.userData.email,
          first_name: data.userData.first_name,
          last_name: data.userData.last_name,
          groups: data.userData.groups
        }));

        console.log('Saved user data:', data.userData); // เพิ่ม log เพื่อตรวจสอบ

        navigate('/mfuchatbot');
      } catch (error) {
        console.error('Callback error:', error);
        navigate('/login');
      }
    };

    handleCallback();
  }, [navigate]);

  return (
    <div className="flex items-center justify-center min-h-screen">
      <div className="text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900 mx-auto"></div>
        <p className="mt-4">กำลังเข้าสู่ระบบ...</p>
      </div>
    </div>
  );
};

export default AuthCallback;

// frontend/src/views/AuthCallback.vue
<script setup>
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import { useLanguage } from '@/composables/useSettings'
import axios from 'axios' // Make sure axios is available or use fetch

const router = useRouter()
const authStore = useAuthStore()
const { t } = useLanguage()

onMounted(async () => {
  const urlParams = new URLSearchParams(window.location.search)
  const code = urlParams.get('code')
  const token = urlParams.get('token') // Legacy/Fallback support
  
  if (code) {
    try {
      // Exchange code for token
      const redirectUri = window.location.origin + '/auth/callback'
      
      console.log('Exchanging code for token...')
      const response = await axios.post('/api/auth/sso/callback', {
        code,
        redirect_uri: redirectUri
      })

      const { token: authToken, user } = response.data
      
      if (authToken && user) {
        authStore.setAuth(authToken, user)
        localStorage.setItem('auth_provider', 'sso')
        console.log('Auth successful:', user)
        router.push('/chat')
      } else {
        throw new Error('Invalid response from server')
      }

    } catch (e) {
      console.error('SSO Exchange Failed:', e)
      router.push('/login?error=auth_failed')
    }
  } else if (token) {
    // Legacy support (if needed, or for testing)
    const userDataB64 = urlParams.get('user_data')
    if (userDataB64) {
      try {
        const userData = JSON.parse(atob(userDataB64))
        authStore.setAuth(token, userData)
        localStorage.setItem('auth_provider', 'legacy')
        router.push('/chat')
      } catch (e) {
        router.push('/login?error=parse_failed')
      }
    }
  } else {
    // No code or token
    const error = urlParams.get('error')
    if (error) {
      router.push(`/login?error=${error}`)
    } else {
      router.push('/login')
    }
  }
})
</script>

<template>
  <div class="callback-container">
    <div class="loader-card fade-in">
      <div class="spinner"></div>
      <p class="loader-text">{{ t('authenticating') }}</p>
      <p class="loader-subtext">{{ t('verifyCreds') }}</p>
    </div>
  </div>
</template>

<style scoped>
.callback-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--color-bg-dark);
}

.loader-card {
  text-align: center;
  padding: 48px;
}

.spinner {
  width: 48px;
  height: 48px;
  border: 4px solid var(--color-border);
  border-top-color: var(--color-primary);
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin: 0 auto 24px;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.loader-text {
  font-size: 18px;
  font-weight: 600;
  color: var(--color-text);
  margin-bottom: 8px;
}

.loader-subtext {
  font-size: 14px;
  color: var(--color-text-muted);
}
</style>
